name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 12345
          MYSQL_DATABASE: restaurants
        ports:
        - 3307:3306

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - run: npm ci
      - run: npx sequelize-cli db:migrate
      - run: npm test
      - run: docker login -u ${{ secrets.ci-cd.DOCKER_USERNAME }} -p ${{ secrets.ci-cd.DOCKER_PASSWORD }}
      - run: docker build -t alexanderukhanov/back .
      - run: docker push alexanderukhanov/back
